#
#     Dockerfile to build GEANT4 on top of centOS+CLEHP+CERNroot
#
#     Robert Varner, ORNL from work by
#        David Tedeschi, Univ. of South Carolina, 2018
#-------------------------------------------------------------------------------
FROM dave:centos_clhep_root
LABEL maintainer "tedeschi@sc.edu"
#
# geant4.10.04.p03
#
# locally build-in version of CERN Geant4
# set dirs and vars
#
RUN mkdir -p /mjsw/GEANT /mjsw/GEANT/build /mjsw/GEANT/install
ENV G4_install_dir /mjsw/GEANT/install
ENV G4_dir geant4.10.04.p03
#
WORKDIR /mjsw/GEANT
ADD geant4.10.04.p03.tar /mjsw/GEANT
#
# build geant
# install_data=OFF avoids slow, long downloads
#
RUN cd build \
    && cmake3 \
    -DCMAKE_INSTALL_PREFIX=${G4_install_dir} \
    -DGEANT4_USE_SYSTEM_CLHEP=ON \
    -DCLHEP_ROOT_DIR=${CLHEP_BASE_DIR} \
    -DGEANT4_INSTALL_DATA=OFF \
    -DGEANT4_USE_RAYTRACER_X11=ON \
    -DGEANT4_USE_OPENGL_X11=ON \
    -DGEANT4_USE_GDML=ON \
    ../${G4_dir} \
    && make -j4 \
    && make install
#
# install data files from local source
# much quicker than download option...
# note - ADD automatically untars
#
ENV G4DATADIR ${G4_install_dir}/share/Geant4-10.4.3/data/
ADD G4PhotonEvaporation.5.2.tar $G4DATADIR
ADD G4EMLOW.7.3.tar             $G4DATADIR
ADD G4NDL.4.5.tar               $G4DATADIR
ADD G4RadioactiveDecay.5.2.tar  $G4DATADIR
ADD G4SAIDDATA1.1.tar           $G4DATADIR
ADD G4ABLA.3.1.tar              $G4DATADIR
ADD G4PII.1.3.tar               $G4DATADIR
ADD G4ENSDFSTATE.2.2.tar        $G4DATADIR
ADD G4RealSurface.2.1.1.tar     $G4DATADIR
ADD G4TENDL.1.3.2.tar           $G4DATADIR
ADD G4NEUTRONXS.1.4.tar         $G4DATADIR
#
# clean up
#
RUN rm -rf /mjsw/GEANT/build
#
WORKDIR /
ENTRYPOINT ["/bin/bash"]
